### ISSUE TITLE
[Bug]:  dependency conflict

### ISSUE THREAD

**Issue by TeslaZY** [infiniflow/ragflow#1824]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

5d55e6a0

### Other environment information

```Markdown
Ubuntu 22.04
```

### Actual behavior

git clone from repo
pip install -r requirements

ERROR: Cannot install -r requirements.txt (line 28), -r requirements.txt (line 35) and mistralai==0.4.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    groq 0.9.0 depends on pydantic<3 and >=1.9.0
    jina 3.27.2 depends on pydantic<2.0.0
    mistralai 0.4.2 depends on pydantic<3 and >=2.5.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Steps to reproduce

```Markdown
pip install -r requirements
```

**Comment by wzncut** [comment]
the same [Bug]

**Comment by wzncut** [comment]
INFO: pip is looking at multiple versions of mistralai to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 28), -r requirements.txt (line 35) and -r requirements.txt (line 39) because these package versions have conflicting dependencies.

The conflict is caused by:
    groq 0.9.0 depends on pydantic<3 and >=1.9.0
    jina 3.27.2 depends on pydantic<2.0.0
    mistralai 0.4.2 depends on pydantic<3 and >=2.5.2
