### ISSUE TITLE
[Bug]: Empty response in Chat Configuration 

### ISSUE THREAD

**Issue by morler** [infiniflow/ragflow#1903]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

dev

### Commit ID

4454ba7

### Other environment information

```Markdown
ASUS Tuf Gaming F15 Pro 13980HX 4060 Laptop Graphics Card
Win11
WSL2
```

### Actual behavior

Chat Settings → Assistant Settings → Empty Response Section.

If you set the content for the empty response, it will cause all questions that do not match the knowledge base to be directed to this empty response, and it will be used as the preferred answer for subsequent similar questions by the assistant.

This will result in the default empty response filling up all the alternative answer options for questions.

![PixPin_2024-08-12_10-52-38](https://github.com/user-attachments/assets/76418a9a-c39c-44d2-a4a8-c187c118466d)

### Steps to reproduce

```Markdown
1. In the empty response option, set a custom reply content;

2. A question for which there is no answer in the knowledge base;

3. A similar question that does have an answer in the knowledge base.
```

### Additional information

I suspect it's related to the "self-rag" mechanism.

**Comment by hangters** [comment]
hi @morler  thank for mention that, I was unable to reproduce this issue. It seems that the problem is related to not recalling any parsing blocks. Could you please check if your knowledge base is set correctly (i.e., if it's set to another knowledge base)? Can the parsing blocks be recalled when you test with questions that have answers in the knowledge base?
 Could you provide more information to help reproduce this issue, such as the name of the chat model used, the embedding model name, the file  parse way , and the files being parsed If it's convenient for you.  Thank you for your assistance.

**Comment by yuzhichang** [comment]
Close due to no response.
