### ISSUE TITLE
[Question]: Planned Integration with Ragflow in Infinity 0.4

### ISSUE THREAD

**Issue by Said-Apollo** [infiniflow/ragflow#2404]
### Describe your problem

It is anticipated that Infinity 0.4 will include integration with Ragflow. Could you provide clarification on how this integration will be implemented? Will Elasticsearch be replaced outright, or will users have the flexibility to choose their preferred search engine?

Additionally, for those already using an alternative search engine (e.g., Typesense), will there be support for integrating existing solutions? My goal is to experiment with various databases and search methods to identify the most suitable option for our use case.

**Comment by yingfeng** [comment]
Infinity will be used an alternative at first. And Elasticsearch will still exist while user could choose which one to use. For some advanced features such as tensor based reranking which is required by some future features, ES based RAGFlow wouldn't provide due to being lack of those functionalities.
Regarding to other search engines, it does not satisfy the requirements, we won't integrate.
For example, typesense is an in-memory solution, it does not support "WAND" for full text search, the hybrid search functionality is much weaker,...,etc.   Other search engines also have similar problems.  RAGFlow aim's to guarantee the eventual effectiveness of RAG, it's not an LLMOps platform, so we'll only integrate the ones that deserve to be integrated, not the ones that are likely to be used
