### ISSUE TITLE
[Feature Request]: When I use postgres as the meta DB, the frontend page still displays MySQL information.

### ISSUE THREAD

**Issue by baifachuan** [infiniflow/ragflow#2503]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

When I don't use MySQL as the database, the frontend page still displays MySQL information.

Because the the frontend page hardcode the mysql and minio info.

the frontend should display the corresponding icon.

**Comment by KevinLiangX** [comment]
hello 
Do we have a version range or recommended version for postgres?

**Comment by KevinHuSh** [comment]
I tested it on the latest one which works well.

**Comment by KevinLiangX** [comment]
thanks  , it's also ok for PostgreSQL 10.12 (Debian 10.12-2.pgdg90+1)

**Comment by EdisonHuangtw** [comment]
Hi ,

Thank you for this amazing project! I’ve been working on setting up the server, and I’m also trying to integrate PostgreSQL instead of the default MySQL configuration. 

Could you guide me on how to properly configure PostgreSQL with the server? 

Here’s what I’ve done so far:
1. Updated the `postgresql` service in `docker-compose.yml`.
2. Adjusted the `.env` file with PostgreSQL credentials.
3. Updated the database configuration in `service.conf`.

However, I’m unsure if I need to make further changes to the server code or initialization scripts.

Any guidance or best practices would be greatly appreciated. Thanks in advance for your help!

**Comment by KevinHuSh** [comment]
set envirement variable `DB_TYPE=postgres`

**Comment by EdisonHuangtw** [comment]
Thanks for your response! Could you clarify in which file I should set the `DB_TYPE=postgres` environment variable? Should it be in `.env`, `docker-compose.yml`, or somewhere else?

I appreciate your help!

**Comment by sieudx** [comment]
> set envirement variable `DB_TYPE=postgres`

 Could you clarify in which file I should set the DB_TYPE=postgres environment variable? Should it be in .env, docker-compose.yml, or somewhere else?

I appreciate your help!

**Comment by KevinHuSh** [comment]
I think it should be in `docker/.env`.
