### ISSUE TITLE
[Bug]:  ERROR: ESConnection.search() got an unexpected keyword argument 'idxnm'

### ISSUE THREAD

**Issue by 425deizhu** [infiniflow/ragflow#3153]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

chat

### Commit ID

425deizhu

### Other environment information

```Markdown
demo.ragflow.io
```

### Actual behavior

I have set the API-key properly and the files have also been parsed successfully, but when I was trying to chat then the error emerged as "ERROR: ESConnection.search() got an unexpected keyword argument 'idxnm'"
![屏幕截图 2024-11-01 180902](https://github.com/user-attachments/assets/46c0da09-ed1c-4af4-b541-149ff85758be)

### Steps to reproduce

```Markdown
as above
```

**Comment by 798610929** [comment]
Me too! So how to fix it?

**Comment by zxchi31** [comment]
我也遇到了，刚装好就遇到。输入docker logs -f ragflow-server后，如下：
(base) PS C:\WINDOWS\system32> docker logs -f ragflow-server
[WARNING] [2024-11-01 20:51:29,550] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-11-01 20:51:29,555] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-11-01 20:51:29,710] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-11-01 20:51:29,715] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
/ragflow/.venv/lib/python3.12/site-packages/scholarly/_scholarly.py:312: SyntaxWarning: invalid escape sequence '\d'
  m = re.search("cites=[\d+,]*", object["citedby_url"])
/ragflow/.venv/lib/python3.12/site-packages/graspologic/align/seedless_procrustes.py:18: SyntaxWarning: invalid escape sequence '\i'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:233: SyntaxWarning: invalid escape sequence '\m'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:338: SyntaxWarning: invalid escape sequence '\m'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:411: SyntaxWarning: invalid escape sequence '\m'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:764: SyntaxWarning: invalid escape sequence '\m'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:857: SyntaxWarning: invalid escape sequence '\m'
  """
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!

        ____   ___    ______ ______ __
       / __ \ /   |  / ____// ____// /____  _      __
      / /_/ // /| | / / __ / /_   / // __ \| | /| / /
     / _, _// ___ |/ /_/ // __/  / // /_/ /| |/ |/ /
    /_/ |_|/_/  |_|\____//_/    /_/ \____/ |__/|__/


/ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:93: SyntaxWarning: invalid escape sequence '\s'
  """
/ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:132: SyntaxWarning: invalid escape sequence '\s'
  """
/ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:234: SyntaxWarning: invalid escape sequence '\s'
  """
[INFO] [2024-11-01 20:51:43,343] [_internal._log] [line:97]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.18.0.6:9380
[INFO] [2024-11-01 20:51:43,345] [_internal._log] [line:97]: Press CTRL+C to quit
/ragflow/.venv/lib/python3.12/site-packages/graspologic/match/wrappers.py:74: SyntaxWarning: invalid escape sequence '\s'
  """
/ragflow/.venv/lib/python3.12/site-packages/graspologic/pipeline/embed/adjacency_spectral_embedding.py:37: SyntaxWarning: invalid escape sequence '\S'
  """
/ragflow/.venv/lib/python3.12/site-packages/graspologic/pipeline/embed/laplacian_spectral_embedding.py:38: SyntaxWarning: invalid escape sequence '\S'
  """
/ragflow/graphrag/entity_resolution.py:181: SyntaxWarning: invalid escape sequence '\d'
  pattern_int = f"{re.escape(entity_index_delimiter)}(\d+){re.escape(entity_index_delimiter)}"
[INFO] [2024-11-01 20:53:13,626] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 20:53:13] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 20:53:13,649] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 20:53:13] "GET /v1/kb/detail?kb_id=84ce71aa981111efadbc0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 20:53:13,663] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 20:53:13] "GET /v1/llm/list HTTP/1.1" 200 -
[INFO] [2024-11-01 20:53:17,165] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 20:53:17] "POST /v1/chunk/retrieval_test HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:30,993] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:30] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:31,009] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:31] "GET /v1/kb/detail?kb_id=84ce71aa981111efadbc0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:31,022] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:31] "GET /v1/llm/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:33,197] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:33] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:33,224] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:33] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:33,260] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:33] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:35,054] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:35] "GET /v1/system/version HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:35,064] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:35] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:37,266] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:37] "GET /v1/user/tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:37,277] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:37] "GET /v1/llm/factories HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:37,291] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:37] "GET /v1/llm/my_llms HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:38,444] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:38] "GET /v1/user/tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:19:38,458] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:19:38] "GET /v1/llm/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:04,659] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:04] "POST /v1/user/set_tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:08,188] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:08] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:08,193] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:08] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:09,611] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:09] "GET /v1/user/tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:09,619] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:09] "GET /v1/kb/detail?kb_id=84ce71aa981111efadbc0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:09,622] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:09] "GET /v1/document/list?kb_id=84ce71aa981111efadbc0242ac120006&keywords=&page_size=10&page=1 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:12,161] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:12] "GET /v1/chunk/knowledge_graph?doc_id=a963d172981111ef855d0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:12,216] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:12] "POST /v1/chunk/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:14,094] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:14] "GET /v1/llm/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:25,677] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:25] "POST /v1/chunk/retrieval_test HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:31,467] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:31] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:31,483] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:31] "GET /v1/dialog/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:31,521] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:31] "GET /v1/dialog/get?dialog_id=86588190981211efb9ed0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:31,530] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:31] "GET /v1/conversation/list?dialog_id=86588190981211efb9ed0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:31,606] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:31] "GET /v1/conversation/get?conversation_id=cb18f94d7e1849d6ba2009b9e0a2a012 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:20:35,595] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:35] "GET /v1/conversation/get?conversation_id=cb18f94d7e1849d6ba2009b9e0a2a012 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/ragflow/api/apps/conversation_app.py", line 181, in stream
    for ans in chat(dia, msg, True, **req):
  File "/ragflow/api/db/services/dialog_service.py", line 210, in chat
    kbinfos = retr.retrieval(" ".join(questions), embd_mdl, tenant_ids, dialog.kb_ids, 1, dialog.top_n,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/nlp/search.py", line 380, in retrieval
    sres = self.search(req, [index_name(tid) for tid in tenant_ids], embd_mdl, highlight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/graphrag/search.py", line 71, in search
    ent_res = self.es.search(deepcopy(s), idxnm=idxnm, timeout="600s", src=src)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ESConnection.search() got an unexpected keyword argument 'idxnm'
[INFO] [2024-11-01 21:20:53,030] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:20:53] "POST /v1/conversation/completion HTTP/1.1" 200 -
[INFO] [2024-11-01 21:22:35,838] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:22:35] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:22:39,984] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:22:39] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:22:39,997] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:22:39] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:22:41,275] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:22:41] "GET /v1/user/tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:22:41,282] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:22:41] "GET /v1/kb/detail?kb_id=84ce71aa981111efadbc0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:22:41,285] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:22:41] "GET /v1/document/list?kb_id=84ce71aa981111efadbc0242ac120006&keywords=&page_size=10&page=1 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:22:43,330] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:22:43] "GET /v1/llm/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:05,695] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:05] "GET /v1/system/version HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:05,723] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:05] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:07,591] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:07] "GET /v1/llm/my_llms HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:07,609] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:07] "GET /v1/user/tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:07,620] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:07] "GET /v1/llm/factories HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:30,944] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:30] "GET /v1/system/token_list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:32,323] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:32] "GET /v1/llm/my_llms HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:32,343] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:32] "GET /v1/user/tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:32,359] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:32] "GET /v1/llm/factories HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:33,674] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:33] "GET /v1/user/tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:33,694] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:33] "GET /v1/llm/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:43,813] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:43] "POST /v1/user/set_tenant_info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:46,965] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:46] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:46,975] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:46] "GET /v1/dialog/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:47,036] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:47] "GET /v1/dialog/get?dialog_id=86588190981211efb9ed0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:47,042] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:47] "GET /v1/conversation/list?dialog_id=86588190981211efb9ed0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:47,091] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:47] "GET /v1/conversation/get?conversation_id=cb18f94d7e1849d6ba2009b9e0a2a012 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:23:54,545] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:23:54] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:24:03,316] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:24:03] "POST /v1/conversation/ask HTTP/1.1" 200 -
[INFO] [2024-11-01 21:24:03,632] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:24:03] "POST /v1/chunk/retrieval_test HTTP/1.1" 200 -
[INFO] [2024-11-01 21:24:05,180] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:24:05] "POST /v1/conversation/related_questions HTTP/1.1" 200 -
[INFO] [2024-11-01 21:24:27,879] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:24:27] "POST /v1/conversation/mindmap HTTP/1.1" 200 -
[INFO] [2024-11-01 21:24:57,164] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:24:57] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:24:57,209] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:24:57] "GET /v1/file/list?parent_id=&keywords=&page_size=10&page=1 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:00,158] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:00] "GET /v1/canvas/templates HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:00,195] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:00] "GET /v1/canvas/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:01,834] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:01] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:02,524] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:02] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:02,529] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:02] "GET /v1/dialog/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:02,583] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:02] "GET /v1/dialog/get?dialog_id=86588190981211efb9ed0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:02,591] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:02] "GET /v1/conversation/list?dialog_id=86588190981211efb9ed0242ac120006 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:02,663] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:02] "GET /v1/conversation/get?conversation_id=cb18f94d7e1849d6ba2009b9e0a2a012 HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:05,627] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:05] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-11-01 21:25:05,643] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:25:05] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:33:50,050] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:33:50] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-11-01 21:33:50,061] [_internal._log] [line:97]: 172.18.0.6 - - [01/Nov/2024 21:33:50] "GET /v1/kb/list HTTP/1.1" 200 -
[WARNING] [2024-11-02 02:15:40,116] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||Connection closed by server.
[WARNING] [2024-11-02 02:15:44,859] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||Error -2 connecting to redis:6379. Name or service not known.
[WARNING] [2024-11-02 02:15:48,576] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||Error -2 connecting to redis:6379. Name or service not known.
[WARNING] [2024-11-02 02:16:31,966] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-11-02 02:16:31,972] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-11-02 02:16:32,570] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-11-02 02:16:32,576] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
/ragflow/.venv/lib/python3.12/site-packages/scholarly/_scholarly.py:312: SyntaxWarning: invalid escape sequence '\d'
  m = re.search("cites=[\d+,]*", object["citedby_url"])
/ragflow/.venv/lib/python3.12/site-packages/graspologic/align/seedless_procrustes.py:18: SyntaxWarning: invalid escape sequence '\i'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:233: SyntaxWarning: invalid escape sequence '\m'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:338: SyntaxWarning: invalid escape sequence '\m'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:411: SyntaxWarning: invalid escape sequence '\m'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:764: SyntaxWarning: invalid escape sequence '\m'
  """
/ragflow/.venv/lib/python3.12/site-packages/ot/gromov/_quantized.py:857: SyntaxWarning: invalid escape sequence '\m'
  """
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!

        ____   ___    ______ ______ __
       / __ \ /   |  / ____// ____// /____  _      __
      / /_/ // /| | / / __ / /_   / // __ \| | /| / /
     / _, _// ___ |/ /_/ // __/  / // /_/ /| |/ |/ /
    /_/ |_|/_/  |_|\____//_/    /_/ \____/ |__/|__/


/ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:93: SyntaxWarning: invalid escape sequence '\s'
  """
/ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:132: SyntaxWarning: invalid escape sequence '\s'
  """
/ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:234: SyntaxWarning: invalid escape sequence '\s'
  """
[INFO] [2024-11-02 02:16:46,434] [_internal._log] [line:97]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.18.0.6:9380
[INFO] [2024-11-02 02:16:46,436] [_internal._log] [line:97]: Press CTRL+C to quit
/ragflow/.venv/lib/python3.12/site-packages/graspologic/match/wrappers.py:74: SyntaxWarning: invalid escape sequence '\s'
  """
/ragflow/.venv/lib/python3.12/site-packages/graspologic/pipeline/embed/adjacency_spectral_embedding.py:37: SyntaxWarning: invalid escape sequence '\S'
  """
/ragflow/.venv/lib/python3.12/site-packages/graspologic/pipeline/embed/laplacian_spectral_embedding.py:38: SyntaxWarning: invalid escape sequence '\S'
  """
/ragflow/graphrag/entity_resolution.py:181: SyntaxWarning: invalid escape sequence '\d'
  pattern_int = f"{re.escape(entity_index_delimiter)}(\d+){re.escape(entity_index_delimiter)}"

**Comment by SummerDream233** [comment]
This is a very serious bug, which prevents the normal use based on knowledge graph construction method.
I try to restart the server, and the problem still remain, including the chat inference and API inference.
If possible, I really hope that you can fix the bug as soon as possible.

**Comment by SummerDream233** [comment]
I would like to add that this issue occurred in the latest version.
I just upgraded to the latest version about two days ago, and before that, there had been no such incidents.

And I noticed that you have recently updated:
2024-11-01 Adds keyword extraction and related question generation to the parsed chunk to improve the accuracy of retrieval.

Is it possible that in this update, each block has a new index, which prevents previously parsed document blocks from being applied to the latest version?

**Comment by alanOO7** [comment]
me too

**Comment by FunkyYang** [comment]
which branch ?

**Comment by zxchi31** [comment]
RAGFLOW_IMAGE=infiniflow/ragflow:dev

&nbsp;


终是幻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Funky ***@***.***&gt;; 
发送时间: 2024年11月13日(星期三) 下午4:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [infiniflow/ragflow] [Bug]:  ERROR: ESConnection.search() got an unexpected keyword argument &#39;idxnm&#39; (Issue #3153)














 
which branch ?
