### ISSUE TITLE
[Question]: use ragflowsdk error

### ISSUE THREAD

**Issue by lvyoudashuju** [infiniflow/ragflow#3218]
### Describe your problem

Currently, the knowledge base ID and document ID can be obtained, but an error is reported when searching. The error message is: Exception: `datasets` is required.
![企业微信截图_17307972468922](https://github.com/user-attachments/assets/35697f00-9eef-4fb5-b333-0f8268fa73d6)

**Comment by Feiue** [comment]
Please update your code to the latest version.

**Comment by lvyoudashuju** [comment]
It needs to be re-
pip install ragflow-sdk==0.13.0?

**Comment by Feiue** [comment]
Sorry, it's not the SDK version, but the Ragflow version.

**Comment by lvyoudashuju** [comment]
I have already installed ragflow 13.0 version.

**Comment by Feiue** [comment]
I have already investigated the cause of this issue and found that it was due to some problems in the SDK version 0.13. This bug was previously fixed, but it might have been resolved only after the release, which led to this issue. The new code has already been submitted, so you can either wait a bit or choose to modify the package causing the error. `"datasets": dataset_ids` to `"dataset_ids": dataset_ids`

**Comment by lvyoudashuju** [comment]
it's OK.I have already changed "datasets": dataset_ids to "dataset_ids": dataset_ids in the ragflow.py。thanks!
