### ISSUE TITLE
[Question]: How to start RagFlow manually ?

### ISSUE THREAD

**Issue by Kryto614** [infiniflow/ragflow#448]
### Describe your problem

How to prevent RagFlow from auto startng, and instead start it manually when needed? My system is Ubuntu.

**Comment by Alphayellowcat** [comment]
@Kryto614 
To set up your Docker project so that containers only start when manually triggered rather than automatically on Docker start, you need to adjust the service settings in your `docker-compose.yml` file. Typically, containers start automatically if they are configured to do so, especially when the `restart` policy is set to `always`.

Here's what you can do:

1. **Modify the Restart Policy**: Locate the `restart` policy in your `docker-compose.yml` for the service you want to control. Change it from `always` to `no`:

```
    services:
      ragflow:
        restart: no

```
    This change ensures that the service won't automatically start when Docker starts.

2. **Starting Containers Manually**: After making the above change, you will need to manually start your containers whenever you need them by using the Docker Compose command:

    ```bash
    docker compose up
    ```

**Comment by Kryto614** [comment]
> @Kryto614 To set up your Docker project so that containers only start when manually triggered rather than automatically on Docker start, you need to adjust the service settings in your `docker-compose.yml` file. Typically, containers start automatically if they are configured to do so, especially when the `restart` policy is set to `always`.
> 
> Here's what you can do:
> 
> 1. **Modify the Restart Policy**: Locate the `restart` policy in your `docker-compose.yml` for the service you want to control. Change it from `always` to `no`:
> 
> ```
>     services:
>       ragflow:
>         restart: no
> ```
> 
> ```
> This change ensures that the service won't automatically start when Docker starts.
> ```
> 
> 2. **Starting Containers Manually**: After making the above change, you will need to manually start your containers whenever you need them by using the Docker Compose command:
>    ```shell
>    docker compose up
>    ```

Thank you, that works for me perfectly !
