### ISSUE TITLE
ragflow-server | peewee.OperationalError:(1045, "Access denied for user 'root'@'{Host}' (using password: YES)")

### ISSUE THREAD

**Issue by ciaoyizhen** [infiniflow/ragflow#480]
### Describe your problem

#450 

In the previous issue I asked this question, I then went into the mysql container via `docker exec -it` and tried to log in using the initial password `infini_rag_flow` with the following command `mysql -u root -p` and it failed, I then realised that in fact the password was empty and that I could log in directly to mysq using `mysql - u root` to log into mysq directly, so I modified the `MySQL_PASSWORD="" ` in the docker/.env file.
But before I encountered root@localhost,now I encountered root@{Host}.After checking the information online, I used the following command
`grant all privileges on *. * to 'root'@'%' with grant option;` Still not working!
Also, the last time I ran it, I couldn't see the ragflow icon, but this time I can see it. I don't know why.
I don't know how to solve this problem

**Comment by ciaoyizhen** [comment]
The .env and yaml files are the same as in the project except for what is mentioned

**Comment by KevinHuSh** [comment]
This is a typical problem when password is wrong. Please check the password in yaml and .env.

**Comment by chhhaya** [comment]
我也遇到这个问题了， 你解决了吗？ @ciaoyizhen

**Comment by xia-huang-411303** [comment]
I have the same problem, the problem is not solved, why shut down the problem.
I changed the passwords in '.env 'and' service_conf.yaml 'and made them the same,
And then I deployed it using docker compose, and then this error,
I'm pretty sure I set the password and keep it the same
server log:
peewee.OperationalError: (1045, "Access denied for user 'root'@'172.25.0.6' (using password: YES)")
mysql log:
2024-08-01T08:01:02.273870Z 189 [Note] Access denied for user 'root'@'172.25.0.6' (using password: YES)

**Comment by xia-huang-411303** [comment]
SHIT， IF I USE defult password `infini_rag_flow`，everything goes right

**Comment by ciaoyizhen** [comment]
我公司有人找到了问题。
好像是因为  mysql那个编码有问题
你自己创一个账号就可以

**Comment by ciaoyizhen** [comment]
反正这代码跟💩一样  我们已经自己做了

**Comment by xia-huang-411303** [comment]
> 我公司有人找到了问题。 好像是因为 mysql那个编码有问题 你自己创一个账号就可以

 Have you ever consider pull request about thisBUG?
非常感谢。

**Comment by hzy50000** [comment]
@ciaoyizhen 你好 请问是要自己进入MySQL容器里新建一个账户 然后yaml和.env都改成自己新建的账户吗
我按照这样操作还是报一样的错

**Comment by coderLinJ5945** [comment]
亲自测试过，修改密码无效，就是镜像隐形埋的一个默认密码的雷，不太关注这里的小白，部署了使用默认密码，如果没有其他外层的安全机制，就可能成为黑客的肉机，如果恶意揣测，打包的人不可能发现不了这么致命的问题。大家顶起来，让更多的人看到！！！考虑换技术方案或者做完整的代码的安全审查工作了

**Comment by coderLinJ5945** [comment]
是使用问题，我这边完美解决了这个问题，解决步骤如下：
问题: docker logs -f 917c48df8473(infiniflow/ragflow:v0.16.0的容器日志)
peewee.OperationalError: (1045, "Access denied for user 'root'@'172.24.0.6' (using password: YES)")

# 问题原因，这个镜像的mysql密码一致是默认密码，只要配置没改全就会报错

解决办法:
1. 停止并移除现有容器
cd ./docker
docker compose -f docker-compose.yml down
2. 删除或备份数据卷
备份命令：
cp -r /home/data/docker/volumes/docker_esdata01 /backup/docker_esdata01_backup
cp -r /home/data/docker/volumes/docker_minio_data /backup/docker_minio_data_backup
cp -r /home/data/docker/volumes/docker_mysql_data /backup/docker_mysql_data_backup
cp -r /home/data/docker/volumes/docker_redis_data /backup/docker_redis_data_backup
删除命令：
docker volume rm docker_esdata01
docker volume rm docker_minio_data
docker volume rm docker_mysql_data
docker volume rm docker_redis_data

3. 删除未使用的网络配置
docker network prune

4. 修改docker/.env 、 docker/service_conf.yaml.template和conf/service_conf.yaml 这三个文件
中所有的密码，设置成自己的，务必这三处都保持一致（重要）
5. 重新启动服务
cd ./docker
[root@localhost docker]# docker compose -f docker-compose.yml up -d
WARN[0000] The "HF_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string. 
[+] Running 10/10
 ✔ Network docker_ragflow      Created                                                                                                                                                                      0.0s 
 ✔ Volume "docker_esdata01"    Created                                                                                                                                                                      0.0s 
 ✔ Volume "docker_mysql_data"  Created                                                                                                                                                                      0.0s 
 ✔ Volume "docker_minio_data"  Created                                                                                                                                                                      0.0s 
 ✔ Volume "docker_redis_data"  Created                                                                                                                                                                      0.0s 
 ✔ Container ragflow-minio     Started                                                                                                                                                                      0.4s 
 ✔ Container ragflow-es-01     Started                                                                                                                                                                      0.4s 
 ✔ Container ragflow-redis     Started                                                                                                                                                                      0.4s 
 ✔ Container ragflow-mysql     Healthy                                                                                                                                                                     10.9s 
 ✔ Container ragflow-server    Started                                                                                                                                                                     11.1s

# 6查看日志看看，没有如下报错了：
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-02-26 10:51:53,554 INFO     20 TaskExecutor: RAGFlow version: v0.16.0 full
2025-02-26 10:51:53,554 INFO     20 Use Elasticsearch http://es01:9200 as the doc engine.
2025-02-26 10:51:53,563 INFO     20 GET http://es01:9200/ [status:200 duration:0.007s]
2025-02-26 10:51:53,566 INFO     20 HEAD http://es01:9200/ [status:200 duration:0.003s]
2025-02-26 10:51:53,566 INFO     20 Elasticsearch http://es01:9200 is healthy.
2025-02-26 10:51:53,572 WARNING  20 Load term.freq FAIL!
2025-02-26 10:51:53,577 WARNING  20 Realtime synonym is disabled, since no redis connection.
2025-02-26 10:51:53,583 WARNING  20 Load term.freq FAIL!
2025-02-26 10:51:53,588 WARNING  20 Realtime synonym is disabled, since no redis connection.
2025-02-26 10:51:53,588 INFO     20 MAX_CONTENT_LENGTH: 134217728
2025-02-26 10:51:53,588 INFO     20 SERVER_QUEUE_MAX_LEN: 1024
2025-02-26 10:51:53,588 INFO     20 SERVER_QUEUE_RETENTION: 3600
2025-02-26 10:51:53,588 INFO     20 MAX_FILE_COUNT_PER_USER: 0
2025-02-26 10:51:53,591 WARNING  20 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-02-26 10:51:53,592 INFO     20 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-02-26T10:51:53.591+08:00", "boot_at": "2025-02-26T10:51:53.554+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}

# 7. 注册登录注册测试：OK

**Comment by 7Yang** [comment]
https://github.com/infiniflow/ragflow/issues/10674#issuecomment-3425628912
